-- Disable ALL profile and auth triggers
ALTER TABLE profiles DISABLE TRIGGER ALL;
ALTER TABLE auth.users DISABLE TRIGGER ALL;
ALTER TABLE occasions DISABLE TRIGGER ALL;
ALTER TABLE access_requests DISABLE TRIGGER ALL;
ALTER TABLE items DISABLE TRIGGER ALL;
ALTER TABLE user_favorites DISABLE TRIGGER ALL;